continents_and_regions = [['Asia',['South Asia','East Asia', 'Southeast Asia']], ['Europe', ['Western Europe','Northern Europe', 'Eastern Europe', 'Southern Europe']],
           ['Oceania', ['Oceania']], ['Africa',['Eastern Africa', 'Sub-Saharan Africa']], ['America',['North America', 'Latin America']]]

types_dict = {'indian': ['Asia', 'South Asia'],
         'cafe': ['Europe', 'Western Europe'],
         'pizza': ['Europe', 'Western Europe'],
         'italian': ['Europe', 'Western Europe'],
         'finnish': ['Europe', 'Northern Europe'],
         'south korean': ['Asia', 'East Asia'],
         'north korean': ['Asia', 'East Asia'],
         'swedish': ['Europe', 'Northern Europe'],
         'vietnamese': ['Asia', 'Southeast Asia'],
         'austrian': ['Europe', 'Western Europe'],
         'australian': ['Oceania', 'Oceania'],
         'german': ['Europe', 'Western Europe'],
         'japanese': ['Asia', 'East Asia'],
         'vegetarian': ['Europe', 'Western Europe'],
         'french': ['Europe', 'Western Europe'],
         'african': ['Africa', 'Eastern Africa'],
         'american': ['America', 'North America'],
         'barbecue': ['America', 'North America'],
         'czech': ['Europe', 'Eastern Europe'],
         'chinese': ['Asia', 'East Asia'],
         'thai': ['Asia', 'Southeast Asia'],
         'mexican': ['America', 'Latin America'],
         'greek': ['Europe', 'Southern Europe'],
         'ethiopian': ['Africa', 'Eastern Africa'],
         'bangladeshi': ['Asia', 'South Asia'],
         'pakistani': ['Asia', 'South Asia'],
         'belgian': ['Europe', 'Western Europe'],
         'canadian': ['America', 'North America'],
         'indonesian': ['Asia', 'Southeast Asia'],
         'polish': ['Europe', 'Eastern Europe'],
         'brazilian': ['America', 'Latin America'],
         'spanish': ['Europe', 'Western Europe'],
         'malaysian': ['Asia', 'Southeast Asia'],
         'sri lankan': ['Asia', 'South Asia']
         }

restaurant_data = [
['Asia', 'South Asia', 'indian', 'Curry House', '4', '3', '26 Spice Street'],
['Europe', 'Western Europe', 'cafe', 'Caffeine Fix', '4', '2', '12 Espresso Lane'],
['Europe', 'Western Europe', 'pizza', 'Slice of Heaven', '5', '3', '18 Pizzeria Road'],
['Europe', 'Western Europe', 'italian', 'Mamma Mia Trattoria', '4', '4', '22 Pasta Avenue'],
['Europe', 'Northern Europe', 'finnish', 'Lakeside Grill', '3', '3', '35 Suomi Street'],
['Asia', 'East Asia', 'south korean', 'Seoul Spice', '4', '4', '9 K-Pop Lane'],
['Asia', 'East Asia', 'north korean', 'Kimchi House', '3', '3', '50 Pyongyang Road'],
['Europe', 'Northern Europe', 'swedish', 'Nordic Feast', '4', '3', '27 Stockholm Square'],
['Asia', 'Southeast Asia', 'vietnamese', 'Pho Fusion', '5', '4', '8 Banh Mi Lane'],
['Europe', 'Western Europe', 'austrian', 'Vienna Schnitzel', '4', '3', '16 Mozart Street'],
['Oceania', 'Oceania', 'australian', 'Outback Grill', '4', '4', '25 Kangaroo Avenue'],
['Europe', 'Western Europe', 'german', 'Bavarian Beer Hall', '4', '3', '32 Oktoberfest Street'],
['Asia', 'East Asia', 'japanese', 'Sakura Sushi Bar', '5', '4', '10 Zen Garden Lane'],
['Europe', 'Western Europe', 'vegetarian', 'Fresh Harvest', '4', '2', '15 Garden Avenue'],
['Europe', 'Western Europe', 'french', 'Le Croissant', '5', '4', '21 Rue de la Baguette'],
['Africa', 'Eastern Africa', 'african', 'Jungle Spice', '4', '3', '30 Safari Road'],
['America', 'North America', 'american', 'Diner\'s Delight', '4', '3', '14 Main Street'],
['America', 'North America', 'barbecue', 'Smoke and Grill', '5', '4', '40 Hickory Road'],
['Europe', 'Eastern Europe', 'czech', 'Prague Palace', '4', '3', '8 Prague Square'],
['Asia', 'East Asia', 'chinese', 'Dragon Wok', '4', '3', '55 Chinatown'],
['Europe', 'Northern Europe', 'swedish', 'Scandinavian Bistro', '4', '3', '27 Nordic Street'],
['Asia', 'Southeast Asia', 'vietnamese', 'Saigon Delights', '4', '4', '9 Pho Lane'],
['Europe', 'Western Europe', 'austrian', 'Alpine Delicacies', '3', '3', '16 Mozart Street'],
['Oceania', 'Oceania', 'australian', 'Down Under Grill', '4', '4', '25 Kangaroo Avenue'],
['Europe', 'Western Europe', 'german', 'Biergarten Haus', '3', '3', '32 Oktoberfest Street'],
['Asia', 'East Asia', 'japanese', 'Tokyo Teppanyaki', '4', '4', '10 Sushi Lane'],
['Europe', 'Western Europe', 'vegetarian', 'Green Garden Cafe', '4', '2', '15 Plant Avenue'],
['Africa', 'Sub-Saharan Africa', 'french', 'La Provence', '4', '3', '21 Rue de la Baguette'],
['Africa', 'Sub-Saharan Africa', 'african', 'Safari Spices', '3', '3', '30 Safari Road'],
['America', 'North America', 'american', 'Burger Haven', '4', '3', '14 Main Street'],
['America', 'North America', 'barbecue', 'Smokehouse BBQ', '5', '4', '40 Smoky Road'],
['Europe', 'Eastern Europe', 'czech', 'Prague Delights', '4', '3', '8 Prague Square'],
['Asia', 'East Asia', 'chinese', 'Peking Dragon', '4', '3', '55 Chinatown'],
['Asia', 'Southeast Asia', 'thai', 'Thai Spice', '4', '3', '12 Curry Street'],
['America', 'North America', 'american', 'Grill House', '5', '3', '19 Grill Avenue'],
['Europe', 'Western Europe', 'italian', 'La Dolce Vita', '4', '4', '26 Pasta Lane'],
['Asia', 'South Asia', 'indian', 'Curry Express', '3', '3', '32 Naan Road'],
['Europe', 'Western Europe', 'french', 'Gourmet Bistro', '5', '4', '21 Rue du Fromage'],
['Africa', 'Eastern Africa', 'african', 'Serengeti Grill', '4', '3', '30 Savanna Road'],
['America', 'Latin America', 'mexican', 'Taco Fiesta', '4', '3', '18 Guacamole Avenue'],
['Asia', 'South Asia', 'indian', 'Spicy Masala', '4', '3', '26 Spice Street'],
['Europe', 'Western Europe', 'cafe', 'The Coffee House', '4', '2', '12 Espresso Lane'],
['Europe', 'Western Europe', 'pizza', 'Pizza Express', '5', '3', '18 Pizzeria Road'],
['America', 'Latin America', 'mexican', 'El Pueblo', '4', '3', '10 Salsa Street'],
['America', 'Latin America', 'mexican', 'Taco Heaven', '5', '4', '15 Burrito Lane'],
['America', 'Latin America', 'mexican', 'Casa de Guacamole', '4', '3', '20 Tortilla Avenue'],
['America', 'Latin America', 'mexican', 'La Cantina', '4', '3', '25 Margarita Street'],
['America', 'Latin America', 'mexican', 'Sabor Mexicano', '5', '4', '30 Fiesta Road'],
['Africa', 'Eastern Africa', 'ethiopian', 'Addis Ababa', '4', '3', '14 Injera Road'],
['Europe', 'Northern Europe', 'norwegian', 'Nordic Delights', '4', '3', '27 Fjord Lane'],
['Asia', 'South Asia', 'pakistani', 'Spice Junction', '4', '3', '19 Masala Avenue'],
['Europe', 'Western Europe', 'belgian', 'Brussels Bistro', '5', '4', '10 Chocolate Street'],
['America', 'North America', 'canadian', 'Maple Diner', '4', '3', '22 Poutine Avenue'],
['Asia', 'Southeast Asia', 'indonesian', 'Bali Bistro', '4', '3', '16 Satay Street'],
['Europe', 'Eastern Europe', 'polish', 'Pierogi Paradise', '4', '3', '12 Pierogi Lane'],
['America', 'Latin America', 'brazilian', 'Rio Grill', '4', '3', '18 Samba Road'],
['Asia', 'South Asia', 'bangladeshi', 'Dhaka Delights', '3', '2', '25 Curry Lane'],
['Europe', 'Southern Europe', 'greek', 'Olive Garden', '4', '3', '32 Olive Street'],
['America', 'North America', 'american', 'Burger Joint', '5', '3', '20 Main Street'],
['Asia', 'East Asia', 'korean', 'Seoul Kitchen', '4', '4', '11 Kimchi Lane'],
['Europe', 'Western Europe', 'spanish', 'Tapas Terrace', '4', '3', '14 Sangria Street'],
['Asia', 'Southeast Asia', 'malaysian', 'Malacca Grill', '4', '3', '16 Nasi Goreng Road'],
['Europe', 'Western Europe', 'dutch', 'Windmill Café', '4', '3', '19 Tulip Lane'],
['Asia', 'East Asia', 'taiwanese', 'Taipei Tea House', '4', '3', '25 Bubble Street'],
['Europe', 'Northern Europe', 'danish', 'Copenhagen Café', '4', '3', '12 Danish Pastry Road'],
['America', 'Latin America', 'peruvian', 'Lima Llama', '4', '3', '18 Ceviche Avenue'],
['Asia', 'South Asia', 'sri lankan', 'Ceylon Spice', '3', '2', '22 Rice and Curry Lane'],
['Europe', 'Eastern Europe', 'russian', 'Moscow Bistro', '4', '3', '10 Blini Street']
]

