continents_and_regions = [['Asia',['South Asia','East Asia', 'Southeast Asia']], ['Europe', ['Western Europe','Northern Europe', 'Eastern Europe']],
           ['Oceania', ['Oceania']], ['Africa',['Eastern Africa']], ['America',['North America']]]

types = ['german', 'japanese', 'vegetarian', 'french', 'african', 'american', 'barbecue', 'czech', 'chinese', 'thai',
         'mexican', 'indian', 'cafe', 'pizza', 'italian', 'finnish', 'south korean', 'north korean', 'swedish', 'vietnamese', 'austrian', 'australian']

restaurant_data = [
['Asia', 'South Asia', 'indian', 'Curry House', '4', '3', '26 Spice Street'],
['Europe', 'Western Europe', 'cafe', 'Caffeine Fix', '4', '2', '12 Espresso Lane'],
['Europe', 'Western Europe', 'pizza', 'Slice of Heaven', '5', '3', '18 Pizzeria Road'],
['Europe', 'Western Europe', 'italian', 'Mamma Mia Trattoria', '4', '4', '22 Pasta Avenue'],
['Europe', 'Northern Europe', 'finnish', 'Lakeside Grill', '3', '3', '35 Suomi Street'],
['Asia', 'East Asia', 'south korean', 'Seoul Spice', '4', '4', '9 K-Pop Lane'],
['Asia', 'East Asia', 'north korean', 'Kimchi House', '3', '3', '50 Pyongyang Road'],
['Europe', 'Northern Europe', 'swedish', 'Nordic Feast', '4', '3', '27 Stockholm Square'],
['Asia', 'Southeast Asia', 'vietnamese', 'Pho Fusion', '5', '4', '8 Banh Mi Lane'],
['Europe', 'Western Europe', 'austrian', 'Vienna Schnitzel', '4', '3', '16 Mozart Street'],
['Oceania', 'Oceania', 'australian', 'Outback Grill', '4', '4', '25 Kangaroo Avenue'],
['Europe', 'Western Europe', 'german', 'Bavarian Beer Hall', '4', '3', '32 Oktoberfest Street'],
['Asia', 'East Asia', 'japanese', 'Sakura Sushi Bar', '5', '4', '10 Zen Garden Lane'],
['Europe', 'Western Europe', 'vegetarian', 'Fresh Harvest', '4', '2', '15 Garden Avenue'],
['Europe', 'Western Europe', 'french', 'Le Croissant', '5', '4', '21 Rue de la Baguette'],
['Africa', 'Eastern Africa', 'african', 'Jungle Spice', '4', '3', '30 Safari Road'],
['America', 'North America', 'american', 'Diner\'s Delight', '4', '3', '14 Main Street'],
['America', 'North America', 'barbecue', 'Smoke and Grill', '5', '4', '40 Hickory Road'],
['Europe', 'Eastern Europe', 'czech', 'Prague Palace', '4', '3', '8 Prague Square'],
['Asia', 'East Asia', 'chinese', 'Dragon Wok', '4', '3', '55 Chinatown'],
['Europe', 'Northern Europe', 'swedish', 'Scandinavian Bistro', '4', '3', '27 Nordic Street'],
['Asia', 'Southeast Asia', 'vietnamese', 'Saigon Delights', '4', '4', '9 Pho Lane'],
['Europe', 'Western Europe', 'austrian', 'Alpine Delicacies', '3', '3', '16 Mozart Street'],
['Oceania', 'Oceania', 'australian', 'Down Under Grill', '4', '4', '25 Kangaroo Avenue'],
['Europe', 'Western Europe', 'german', 'Biergarten Haus', '3', '3', '32 Oktoberfest Street'],
['Asia', 'East Asia', 'japanese', 'Tokyo Teppanyaki', '4', '4', '10 Sushi Lane'],
['Europe', 'Western Europe', 'vegetarian', 'Green Garden Cafe', '4', '2', '15 Plant Avenue'],
['Africa', 'Sub-Saharan Africa', 'french', 'La Provence', '4', '3', '21 Rue de la Baguette'],
['Africa', 'Sub-Saharan Africa', 'african', 'Safari Spices', '3', '3', '30 Safari Road'],
['America', 'North America', 'american', 'Burger Haven', '4', '3', '14 Main Street'],
['America', 'North America', 'barbecue', 'Smokehouse BBQ', '5', '4', '40 Smoky Road'],
['Europe', 'Eastern Europe', 'czech', 'Prague Delights', '4', '3', '8 Prague Square'],
['Asia', 'East Asia', 'chinese', 'Peking Dragon', '4', '3', '55 Chinatown'],
['Asia', 'Southeast Asia', 'thai', 'Thai Spice', '4', '3', '12 Curry Street'],
['America', 'North America', 'american', 'Grill House', '5', '3', '19 Grill Avenue'],
['Europe', 'Western Europe', 'italian', 'La Dolce Vita', '4', '4', '26 Pasta Lane'],
['Asia', 'South Asia', 'indian', 'Curry Express', '3', '3', '32 Naan Road'],
['Europe', 'Western Europe', 'french', 'Gourmet Bistro', '5', '4', '21 Rue du Fromage'],
['Africa', 'Eastern Africa', 'african', 'Serengeti Grill', '4', '3', '30 Savanna Road'],
['America', 'Latin America', 'mexican', 'Taco Fiesta', '4', '3', '18 Guacamole Avenue'],
['Asia', 'South Asia', 'indian', 'Spicy Masala', '4', '3', '26 Spice Street'],
['Europe', 'Western Europe', 'cafe', 'The Coffee House', '4', '2', '12 Espresso Lane'],
['Europe', 'Western Europe', 'pizza', 'Pizza Express', '5', '3', '18 Pizzeria Road'],
['Europe', 'Western Europe', 'italian', 'Trattoria Romana', '4', '4', '22 Pasta Avenue']
]

